### ISSUE TITLE
Getting Error while running the index.js

### ISSUE THREAD

**Issue by chitranjan-gupta** [chitranjan-gupta/Student-ID#3]
Running the command on terminal on github codespace : `$ node index.js`
I am getting this error
/workspaces/Student-ID/node_modules/@aries-framework/core/build/modules/dids/services/DidResolverService.js:52
            throw new error_1.AriesFrameworkError(`Unable to resolve did document for did '${did}': ${error} ${message}`);
                  ^
AriesFrameworkError: Unable to resolve did document for did 'undefined': invalidDid undefined
    at DidResolverService.resolveDidDocument (/workspaces/Student-ID/node_modules/@aries-framework/core/build/modules/dids/services/DidResolverService.js:52:19)
    at async DidsApi.import (/workspaces/Student-ID/node_modules/@aries-framework/core/build/modules/dids/DidsApi.js:100:27)
    at async run (file:///workspaces/Student-ID/index.js:111:5) {
  [cause]: undefined
}

Node.js v20.5.1

**Comment by chitranjan-gupta** [comment]
Fixed the issue
