### ISSUE TITLE
RNCConfigModule error appears while running the client-app

### ISSUE THREAD

**Issue by chitranjan-gupta** [chitranjan-gupta/Student-ID#5]
After Building the client-app and installing on the device
When the app start and crashes after showing the Splash screen

Error:

09-08 13:27:45.889 13150 13174 E AndroidRuntime: FATAL EXCEPTION: create_react_context
09-08 13:27:45.889 13150 13174 E AndroidRuntime: Process: com.chitranjan.studentid, PID: 13150
09-08 13:27:45.889 13150 13174 E AndroidRuntime: java.lang.IllegalStateException: Native module RNCConfigModule tried to override RNCConfigModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
09-08 13:27:45.889 13150 13174 E AndroidRuntime:        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:55)
09-08 13:27:45.889 13150 13174 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1456)
09-08 13:27:45.889 13150 13174 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1427)
09-08 13:27:45.889 13150 13174 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1338)
09-08 13:27:45.889 13150 13174 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:135)
09-08 13:27:45.889 13150 13174 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1109)
09-08 13:27:45.889 13150 13174 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)

**Comment by chitranjan-gupta** [comment]
Fixed with the help of [module](https://github.com/luggit/react-native-config)
