### ISSUE TITLE
RNGestureHandlerRootView not found error while running the client-app

### ISSUE THREAD

**Issue by chitranjan-gupta** [chitranjan-gupta/Student-ID#6]
After Building the client-app and installing on the device
When the app start and crashes after showing the Splash screen

Error:

09-08 17:50:54.944 21033 21070 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
09-08 17:50:54.944 21033 21070 E AndroidRuntime: Process: com.chitranjan.studentid, PID: 21033
09-08 17:50:54.944 21033 21070 E AndroidRuntime: com.facebook.react.common.JavascriptException: Invariant Violation: requireNativeComponent: "RNGestureHandlerRootView" was not found in the UIManager.
09-08 17:50:54.944 21033 21070 E AndroidRuntime:
09-08 17:50:54.944 21033 21070 E AndroidRuntime: This error is located at:
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in RNGestureHandlerRootView
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in GestureHandlerRootView
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in StackView
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in PreventRemoveProvider
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in NavigationContent
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in Unknown
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in StackNavigator
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in App
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in EnsureSingleNavigator
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in BaseNavigationContainer
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in ThemeProvider
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in NavigationContainerInner
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in _default
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in RCTView
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in Unknown
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in RCTView
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in Unknown
09-08 17:50:54.944 21033 21070 E AndroidRuntime:     in AppContainer, js engine: hermes, stack:
09-08 17:50:54.944 21033 21070 E AndroidRuntime: invariant@1:90939
09-08 17:50:54.944 21033 21070 E AndroidRuntime: getNativeComponentAttributes@1:116101
09-08 17:50:54.944 21033 21070 E AndroidRuntime: anonymous@1:384443
09-08 17:50:54.944 21033 21070 E AndroidRuntime: anonymous@1:112072
09-08 17:50:54.944 21033 21070 E AndroidRuntime: completeWork@1:353209
09-08 17:50:54.944 21033 21070 E AndroidRuntime: completeUnitOfWork@1:366008
09-08 17:50:54.944 21033 21070 E AndroidRuntime: performUnitOfWork@1:365853
09-08 17:50:54.944 21033 21070 E AndroidRuntime: workLoopSync@1:365720
09-08 17:50:54.944 21033 21070 E AndroidRuntime: renderRootSync@1:365604
09-08 17:50:54.944 21033 21070 E AndroidRuntime: performSyncWorkOnRoot@1:363092
09-08 17:50:54.944 21033 21070 E AndroidRuntime: flushSyncCallbacks@1:328192
09-08 17:50:54.944 21033 21070 E AndroidRuntime: scheduleUpdateOnFiber@1:360555
09-08 17:50:54.944 21033 21070 E AndroidRuntime: updateContainer@1:370986
09-08 17:50:54.944 21033 21070 E AndroidRuntime: anonymous@1:380129
09-08 17:50:54.944 21033 21070 E AndroidRuntime: renderElement@1:95679
09-08 17:50:54.944 21033 21070 E AndroidRuntime: renderApplication@1:290824
09-08 17:50:54.944 21033 21070 E AndroidRuntime: run@1:283914
09-08 17:50:54.944 21033 21070 E AndroidRuntime: runApplication@1:284380
09-08 17:50:54.944 21033 21070 E AndroidRuntime: __callFunction@1:99336
09-08 17:50:54.944 21033 21070 E AndroidRuntime: anonymous@1:97832
09-08 17:50:54.944 21033 21070 E AndroidRuntime: __guard@1:98770
09-08 17:50:54.944 21033 21070 E AndroidRuntime: callFunctionReturnFlushedQueue@1:97790
09-08 17:50:54.944 21033 21070 E AndroidRuntime:
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at com.facebook.jni.NativeRunnable.run(Native Method)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
09-08 17:50:54.944 21033 21070 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)

**Comment by chitranjan-gupta** [comment]
Fixed with help of stackoverflow [question](https://stackoverflow.com/questions/71396210/rngesturehandlerrootview-was-not-found-in-the-uimanager)
